### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by rain-1** [ricardbejarano/nginx#2]
Hi, I tried docker build musl and it seemed to compile everything but the final step failed:

```
...
Step 17/22 : FROM scratch
 ---> 
Step 18/22 : COPY rootfs /
COPY failed: stat /var/lib/docker/tmp/docker-builder653757674/rootfs: no such file or directory
```

Do you have any tips, what should I do to build it?

**Comment by ricardbejarano** [comment]
Hi!

You must give Docker a build context where the `rootfs` directory exists, so you must specify the Dockerfile.

Try the following:

```bash
$ git clone https://github.com/ricardbejarano/nginx
$ cd nginx
$ docker build -t nginx:musl -f musl/Dockerfile .
```

_To build the `glibc`-based image, just replace `musl` with `glibc` in the `docker build` command._

I'm adding these instructions to the `README.md` file to avoid future issues like this one. Thanks for pointing this out!

**Comment by ricardbejarano** [comment]
I'll close tomorrow or upon confirmation that you successfully built the image.
